### ISSUE TITLE
Renko backtest

### ISSUE THREAD

**Issue by DaveAndersonCo** [afhacker/cAlgo.API.Extensions.Series#2]
Hi,

I think this library is broken. Following this post https://ctrader.com/forum/third-party-products/22572 , I am trying to run the example in the post but it fails on OnTick() with an not implemented exception from inside the library, inside 'IndicatorMarketSeries' :

public DataSeries OpenPrices => throw new NotImplementedException();

I looked into it a bit and see that in the past updates the 'Bars' has been partially implemented and therefore it doesn't work.
Unfortunately the earlier commits have other bugs and make them useless.

Would you like to see if this can be fixed? It would be a shame for the effort that went into this great idea :-)

Regards,
Dave

**Comment by amusleh-spotware-com** [comment]
I'm aware of the issues, I will fix the issues whenever I got some free time.

**Comment by amusleh-spotware-com** [comment]
The issues has been resolved.

**Comment by DaveAndersonCo** [comment]
Hi afhacker,

Great job on this.  I really appreciate it.

But unfortunately I think it is not completely fixed. Your example on this post https://ctrader.com/forum/third-party-products/22572?page=1#post-1 still doesn't work.

I think it has to do with this issue: https://ctrader.com/forum/calgo-support/23880#post-2

Therefore your great RenkoBars cannot be used with any indicator.

This would be the exception on initializing any indicator:
**Unable to cast object of type 'cAlgo.API.Extensions.Series.RenkoBars' to type 'cTrader.Automate.Small.V1.MarketApi.ISmallChartSource'.**

Unless you come up with something ingenious again ;-)
